package DCRSApp;

/**
* DCRSApp/corbaInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/WEB/eclipse-workspace/CORBA/src/corbaInterface.idl
* Monday, November 5, 2018 12:44:59 PM EST
*/

public final class corbaInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public DCRSApp.corbaInterface value = null;

  public corbaInterfaceHolder ()
  {
  }

  public corbaInterfaceHolder (DCRSApp.corbaInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DCRSApp.corbaInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DCRSApp.corbaInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DCRSApp.corbaInterfaceHelper.type ();
  }

}
