package DCRSApp;


/**
* DCRSApp/corbaInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/WEB/eclipse-workspace/CORBA/src/corbaInterface.idl
* Monday, November 5, 2018 12:44:59 PM EST
*/

public interface corbaInterfaceOperations 
{
  String addCourse (String courseID, String semester, int capacity);
  String removeCourse (String courseID, String semester);
  String listCourseAvailability (String semester);
  String enrollCourse (String studentID, String courseID, String semester);
  String getClassSchedule (String studentID);
  String dropCourse (String studentID, String courseID);
  String swapCourse (String studentID, String oldcourseID, String newcourseID);
} // interface corbaInterfaceOperations
